package org.example;// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class RedminetestbasefirstTestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void redminetestbasefirstTest() {
        driver.get("http://redmine.testbase.ru/");
        driver.manage().window().setSize(new Dimension(1920, 973));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("username")).sendKeys("dasha");
        driver.findElement(By.id("password")).sendKeys("dasha613");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("")).click();
        driver.findElement(By.linkText("Projects")).click();
        driver.findElement(By.linkText("Test")).click();
        driver.findElement(By.linkText("Issues")).click();
        driver.findElement(By.linkText("New issue")).click();
        driver.findElement(By.id("issue_subject")).sendKeys("Selenium created issu");
        driver.findElement(By.id("issue_subject")).sendKeys("Selenium created issue");
        driver.findElement(By.id("issue_description")).sendKeys("Selenium created description");
        driver.findElement(By.id("issue_due_date")).sendKeys("0002-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("0020-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("0200-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("0002-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("0020-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("0202-01-02");
        driver.findElement(By.id("issue_due_date")).sendKeys("2025-01-02");
        driver.findElement(By.name("commit")).click();
        driver.findElement(By.cssSelector("html")).click();
    }
}
